# Generated by Django 5.2.12 on 2026-03-25 07:23

from django.db import migrations


def populate_project_data(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')

    # For existing projects, copy title to project_title and set leader to student
    for project in Project.objects.all():
        if not project.project_title and hasattr(project, 'title'):
            project.project_title = project.title
        if not project.leader:
            project.leader = project.student
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_contactmessage_remove_project_title_project_leader_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_project_data),
    ]
