# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20260325_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='activity_logs', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='activity_logs', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
