# Generated by Django 5.2.12 on 2026-04-10 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='annotated_file',
            field=models.FileField(blank=True, help_text='Upload the annotated version of the document with comments.', null=True, upload_to='annotated_chapters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
