# Generated by Django 5.2.12 on 2026-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_feedback_annotated_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='defense_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled date and time for project defense', null=True),
        ),
    ]
